package br.com.spring.back.coffeSnugPlace.Enum;

public enum TypeCoffee {

	/**
	 * ESPRESSO,CAFE_COM_LEITE, MUCHE, CAPPUCCINO, CAPPUCCINO_ITALIANO,
	 * 	PINGADO, MEDIA, MACCHIATO, CAFE_COM_PANNA, CAFE_COM_CHANTILLY
	 */
	ESPRESSO, COFFEE_WITH_MILK, MUCHE, CAPPUCCINO, CAPPUCCINO_ITALIAN,
		DRIPPED, MEDIA, MACCHIATO, COFFEE_WITH_PANNA, COFFEE_WITH_CHANTILLY
}
